name: Upload to 1B Folder

on:
  push:
    branches: [ main ]
    paths:
      - 'test/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  upload-to-1b:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install PyGithub
    
    - name: Upload files to 1B folder
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -c "
        import os
        import base64
        from github import Github
        
        # Initialize GitHub client
        g = Github(os.environ['GITHUB_TOKEN'])
        repo = g.get_repo('Philosamphy/MobileApp')
        
        # Get all files from test directory
        test_dir = 'test'
        if os.path.exists(test_dir):
            for root, dirs, files in os.walk(test_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    # Calculate relative path
                    relative_path = os.path.relpath(file_path, test_dir)
                    # Build target path (in 1B folder)
                    target_path = f'1B/{relative_path}'
                    
                    try:
                        # Read file content
                        with open(file_path, 'rb') as f:
                            content = f.read()
                        
                        # Check if file already exists
                        try:
                            existing_file = repo.get_contents(target_path)
                            # If file exists, update it
                            repo.update_file(
                                target_path,
                                f'Update {file} via CI/CD',
                                content,
                                existing_file.sha
                            )
                            print(f'Updated: {target_path}')
                        except:
                            # If file doesn't exist, create it
                            repo.create_file(
                                target_path,
                                f'Add {file} via CI/CD',
                                content
                            )
                            print(f'Created: {target_path}')
                    except Exception as e:
                        print(f'Error processing {file_path}: {e}')
        else:
            print('Test directory not found')
        "
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Upload files to 1B folder via CI/CD" || echo "No changes to commit"
        git push 